### ISSUE TITLE
Implement node merging

### ISSUE THREAD

**Issue by nichtich** [pg-format/pg-formatter#48]
[Node merging](https://pg-format.github.io/specification/#node-merging) should be applied before passing to blitzboard to avoid `NodeDuplicationError`.

**Comment by nichtich** [comment]
[Test case](https://pg-format.github.io/pg-formatter/?pg=a+name%3A%22Alice%22%0Aa+%3APerson):

~~~pg
a name:"Alice"
a :Person
~~~

**Comment by hchiba1** [comment]
Fixed by 2c46893 07085f9 1cd6083
