### ISSUE TITLE
Missing Graph if Colon in Node

### ISSUE THREAD

**Issue by SmtB4** [pg-format/pg-formatter#50]
The Graph is will be missing if a colon is put in the Node Id.

```
"http://example.org" -> "http://example2.org"
```

**Comment by hchiba1** [comment]
Fixed by 60508d2 22b73ed

**Comment by nichtich** [comment]
Thanks! Works now: https://pg-format.github.io/pg-formatter/?pg=%22http%3A%2F%2Fexample.org%22+-%3E+%22http%3A%2F%2Fexample2.org%22
